export const articles = [
  {
    uri: "nyt://article/ac950d9b-ebe2-58e2-af22-c6f00de9fbb5",
    url: "https://www.nytimes.com/2021/09/06/arts/michael-k-williams-dead.html",
    id: 100000007958619,
    asset_id: 100000007958619,
    source: "New York Times",
    published_date: "2021-09-06",
    updated: "2021-09-08 12:03:41",
    section: "Arts",
    subsection: "",
    nytdsection: "arts",
    adx_keywords:
      "Deaths (Obituaries);Television;Actors and Actresses;Williams, Michael Kenneth",
    column: null,
    byline: "By Julia Jacobs, Annie Correal, Matthew Haag and Jeremy Egner",
    type: "Article",
    title: "Michael K. Williams, Omar From ‘The Wire,’ Is Dead at 54",
    abstract:
      "Mr. Williams, who also starred in “Boardwalk Empire” and “Lovecraft Country,” was best known for his role as Omar Little in the David Simon HBO series.",
    des_facet: ["Deaths (Obituaries)", "Television", "Actors and Actresses"],
    org_facet: [],
    per_facet: ["Williams, Michael Kenneth"],
    geo_facet: [],
    media: [
      {
        type: "image",
        subtype: "photo",
        caption:
          "Michael K. Williams at the Nostrand Avenue basketball court in the Flatbush neighborhood of Brooklyn in 2017. His work frequently examined the intersection of race, masculinity, crime and institutional failure.",
        copyright: "Demetrius Freeman for The New York Times",
        approved_for_syndication: 1,
        "media-metadata": [
          {
            url: "https://static01.nyt.com/images/2021/09/07/obituaries/07michaelwilliams-obit1-sub/07michaelwilliams-obit1-sub-thumbStandard.jpg",
            format: "Standard Thumbnail",
            height: 75,
            width: 75,
          },
          {
            url: "https://static01.nyt.com/images/2021/09/07/obituaries/07michaelwilliams-obit1-sub/07michaelwilliams-obit1-sub-mediumThreeByTwo210.jpg",
            format: "mediumThreeByTwo210",
            height: 140,
            width: 210,
          },
          {
            url: "https://static01.nyt.com/images/2021/09/07/obituaries/07michaelwilliams-obit1-sub/07michaelwilliams-obit1-sub-mediumThreeByTwo440.jpg",
            format: "mediumThreeByTwo440",
            height: 293,
            width: 440,
          },
        ],
      },
    ],
    eta_id: 0,
  },
  {
    uri: "nyt://article/09892e40-c661-528a-9ef1-3d9c8e4800db",
    url: "https://www.nytimes.com/2021/08/20/us/abbott-covid-tests.html",
    id: 100000007925016,
    asset_id: 100000007925016,
    source: "New York Times",
    published_date: "2021-08-20",
    updated: "2021-08-21 10:42:32",
    section: "U.S.",
    subsection: "",
    nytdsection: "u.s.",
    adx_keywords:
      "Coronavirus (2019-nCoV);Tests (Medical);Layoffs and Job Reductions;Factories and Manufacturing;Abbott Laboratories;Westbrook (Me)",
    column: null,
    byline: "By Sheri Fink",
    type: "Article",
    title: "Maker of Popular Covid Test Told Factory to Destroy Inventory",
    abstract:
      "One of the leading producers of rapid tests purged supplies and laid off workers as sales dwindled. Weeks later, the U.S. is facing a surge in infections with diminished capacity.",
    des_facet: [
      "Coronavirus (2019-nCoV)",
      "Tests (Medical)",
      "Layoffs and Job Reductions",
      "Factories and Manufacturing",
    ],
    org_facet: ["Abbott Laboratories"],
    per_facet: [],
    geo_facet: ["Westbrook (Me)"],
    media: [],
    eta_id: 0,
  },
];
